Traceback (most recent call last):
  File "/miniconda/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/miniconda/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/miniconda/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/miniconda/lib/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/miniconda/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/miniconda/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/miniconda/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#+

# import the necessary functions from rpy2
import rpy2.robjects as robjects
from rpy2.robjects import r, pandas2ri
from rpy2.robjects.packages import importr
pandas2ri.activate()

# import the BayesFactor package
BayesFactor = importr('BayesFactor')

# import the data frames into the R workspace
robjects.globalenv["smoker_sample"] = smoker_sample
robjects.globalenv["nonsmoker_sample"] = nonsmoker_sample

# perform the standard t-test
ttest_output = r('print(t.test(smoker_sample$AvgAlcohol, nonsmoker_sample$AvgAlcohol, alternative="greater"))')

# compute the Bayes factor
r('bf = ttestBF(y=nonsmoker_sample$AvgAlcohol, x=smoker_sample$AvgAlcohol, nullInterval = c(0, Inf))')
r('print(bf[1]/bf[2])')

#-
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[6], line 4[0m
[1;32m      1[0m [38;5;66;03m#+[39;00m
[1;32m      2[0m 
[1;32m      3[0m [38;5;66;03m# import the necessary functions from rpy2[39;00m
[0;32m----> 4[0m [38;5;28;01mimport[39;00m [38;5;21;01mrpy2[39;00m[38;5;21;01m.[39;00m[38;5;21;01mrobjects[39;00m [38;5;28;01mas[39;00m [38;5;21;01mrobjects[39;00m
[1;32m      5[0m [38;5;28;01mfrom[39;00m [38;5;21;01mrpy2[39;00m[38;5;21;01m.[39;00m[38;5;21;01mrobjects[39;00m [38;5;28;01mimport[39;00m r, pandas2ri
[1;32m      6[0m [38;5;28;01mfrom[39;00m [38;5;21;01mrpy2[39;00m[38;5;21;01m.[39;00m[38;5;21;01mrobjects[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpackages[39;00m [38;5;28;01mimport[39;00m importr

[0;31mModuleNotFoundError[0m: No module named 'rpy2'

